name: CI

on:
 push:
   branches:
   - master

jobs:
  build-qq-ci: #job名称

    runs-on: ubuntu-latest #运行环境

    steps:
    
	#第一步：获取小程序源码
    - name: Checkout 
      uses: actions/checkout@master
      
	#第二步：上传小程序版本到管理端，并将此版本设置为体验版（设置体验版可选）
    - name: Build 
      uses: docker://qqminiapp/build:latest 
      env: 
        PLUGIN_VERSION: 1.0.0
        PLUGIN_DESC: CI自动构建上传
        PLUGIN_APPTOKEN: ${{ secrets.APPTOKEN }}
        PLUGIN_BUILDUSER: ${{ github.actor }} 
        PLUGIN_EXPERIENCE: true 
